[package]
name = "repo_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rustpython-parser = "0.3.1"
tree-sitter = "0.20.10"
tree-sitter-javascript = "0.20.1"
tree-sitter-python = "0.20" 
git2 = "0.19.0"